project:
  type: website

website:
  title: "MattMaslowBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/matthew-maslow/
format:
  html:
    theme: solar
    css: styles.css



