project:
  type: website
  output-dir: docs
  
website:
  title: "MattMaslowBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mjmasl01/MattMaslowBlog.git
      - icon: linkedin
        href: https://www.linkedin.com/in/matthew-maslow/
format:
  html:
    theme: solar
    css: styles.css



