{
  "hash": "c1fc985cc737147f510f51212e400a9a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Mini Project 3: Study of # Satellites per Crab\"\nauthor: \"Matthew Maslow\"\ndate: \"February 2, 2024\"\ncategories: [Mini Projects, code, analysis]\n---\n\n\n![crab](crab.png)\n\n# Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(leaps)\nlibrary(reactable)\n# source(\"code_initial_version/plotPoissonDevRes.R\")\n```\n:::\n\n\n# Read in Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrab <- read_csv(\"crab.csv\")\ncrab$Color = as.factor(crab$Color)\ncrab$Spine = as.factor(crab$Spine)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable <- reactable(crab, searchable = TRUE, filterable = TRUE, defaultPageSize = 10, striped = TRUE, bordered = TRUE, highlight = TRUE, outlined = TRUE, onClick = \"select\")\ntable\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"reactable html-widget html-fill-item\" id=\"htmlwidget-e50f11221726b475b3b1\" style=\"width:auto;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e50f11221726b475b3b1\">{\"x\":{\"tag\":{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Color\":[\"3\",\"4\",\"2\",\"4\",\"4\",\"3\",\"2\",\"4\",\"3\",\"4\",\"4\",\"3\",\"3\",\"5\",\"3\",\"2\",\"3\",\"3\",\"5\",\"3\",\"3\",\"2\",\"3\",\"4\",\"5\",\"5\",\"3\",\"3\",\"5\",\"3\",\"2\",\"2\",\"3\",\"3\",\"3\",\"5\",\"3\",\"3\",\"5\",\"3\",\"4\",\"2\",\"2\",\"3\",\"4\",\"4\",\"3\",\"3\",\"3\",\"3\",\"5\",\"3\",\"2\",\"3\",\"3\",\"3\",\"3\",\"4\",\"3\",\"5\",\"4\",\"4\",\"4\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"4\",\"4\",\"3\",\"4\",\"3\",\"4\",\"3\",\"4\",\"3\",\"4\",\"5\",\"4\",\"4\",\"3\",\"5\",\"3\",\"5\",\"5\",\"3\",\"3\",\"3\",\"5\",\"3\",\"4\",\"3\",\"4\",\"4\",\"4\",\"4\",\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"3\",\"3\",\"5\",\"5\",\"4\",\"3\",\"4\",\"4\",\"2\",\"4\",\"3\",\"3\",\"3\",\"4\",\"5\",\"3\",\"3\",\"2\",\"3\",\"3\",\"5\",\"3\",\"3\",\"3\",\"4\",\"3\",\"3\",\"3\",\"3\",\"4\",\"3\",\"3\",\"5\",\"3\",\"3\",\"4\",\"3\",\"3\",\"3\",\"3\",\"3\",\"5\",\"3\",\"3\",\"3\",\"4\",\"4\",\"3\",\"3\",\"3\",\"5\",\"3\",\"3\",\"4\",\"4\",\"4\",\"4\",\"2\",\"5\",\"3\"],\"Spine\":[\"3\",\"3\",\"1\",\"3\",\"3\",\"3\",\"1\",\"2\",\"1\",\"3\",\"3\",\"3\",\"3\",\"2\",\"1\",\"1\",\"3\",\"3\",\"3\",\"3\",\"2\",\"2\",\"1\",\"3\",\"3\",\"3\",\"3\",\"1\",\"3\",\"3\",\"1\",\"3\",\"2\",\"1\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"1\",\"1\",\"1\",\"1\",\"3\",\"3\",\"3\",\"3\",\"1\",\"3\",\"3\",\"1\",\"3\",\"1\",\"3\",\"3\",\"3\",\"1\",\"3\",\"3\",\"3\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"2\",\"3\",\"3\",\"3\",\"2\",\"3\",\"3\",\"1\",\"3\",\"3\",\"3\",\"1\",\"3\",\"2\",\"1\",\"1\",\"3\",\"1\",\"3\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"1\",\"3\",\"3\",\"3\",\"2\",\"3\",\"3\",\"3\",\"1\",\"2\",\"3\",\"1\",\"3\",\"3\",\"3\",\"1\",\"3\",\"2\",\"3\",\"1\",\"3\",\"3\",\"1\",\"3\",\"3\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"1\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"1\",\"3\",\"2\"],\"Width\":[28.3,22.5,26,24.8,26,23.8,26.5,24.7,23.7,25.6,24.3,25.8,28.2,21,26,27.1,25.2,29,24.7,27.4,23.2,25,22.5,26.7,25.8,26.2,28.7,26.8,27.5,24.9,29.3,25.8,25.7,25.7,26.7,23.7,26.8,27.5,23.4,27.9,27.5,26.1,27.7,30,28.5,28.9,28.2,25,28.5,30.3,24.7,27.7,27.4,22.9,25.7,28.3,27.2,26.2,27.8,25.5,27.1,24.5,27,26,28,30,29,26.2,26.5,26.2,25.6,23,23,25.4,24.2,22.9,26,25.4,25.7,25.1,24.5,27.5,23.1,25.9,25.8,27,28.5,25.5,23.5,24,29.7,26.8,26.7,28.7,23.1,29,25.5,26.5,24.5,28.5,28.2,24.5,27.5,24.7,25.2,27.3,26.3,29,25.3,26.5,27.8,27,25.7,25,31.9,23.7,29.3,22,25,27,23.8,30.2,26.2,24.2,27.4,25.4,28.4,22.5,26.2,24.9,24.5,25.1,28,25.8,27.9,24.9,28.4,27.2,25,27.5,33.5,30.5,29,24.3,25.8,25,31.7,29.5,24,30,27.6,26.2,23.1,22.9,24.5,24.7,28.3,23.9,23.8,29.8,26.5,26,28.2,25.7,26.5,25.8,24.1,26.2,26.1,29,28,27,24.5],\"Satellite\":[8,0,9,0,4,0,0,0,0,0,0,0,11,0,14,8,1,1,0,5,4,3,1,2,3,0,3,5,0,0,4,0,0,8,5,0,0,6,0,6,3,5,6,5,9,4,6,4,3,3,5,5,6,4,5,15,3,3,0,0,0,5,3,5,1,8,10,0,0,3,7,1,0,6,0,0,3,4,0,5,0,0,0,4,0,3,0,0,0,0,5,0,0,0,0,1,0,1,1,1,1,1,1,4,1,1,1,1,2,4,3,6,0,2,2,0,12,0,5,6,6,2,0,2,3,0,3,4,2,6,6,0,4,10,7,0,5,5,6,6,7,3,3,0,0,8,4,4,10,9,4,0,0,0,0,4,0,2,0,4,4,3,8,0,7,0,0,2,3,4,0,0,0],\"Weight\":[3050,1550,2300,2100,2600,2100,2350,1900,1950,2150,2150,2650,3050,1850,2300,2950,2000,3000,2200,2700,1950,2300,1600,2600,2000,1300,3150,2700,2600,2100,3200,2600,2000,2000,2700,1850,2650,3150,1900,2800,3100,2800,2500,3300,3250,2800,2600,2100,3000,3600,2100,2900,2700,1600,2000,3000,2700,2300,2750,2250,2550,2050,2450,2150,2800,3050,3200,2400,1300,2400,2800,1650,1800,2250,1900,1600,2200,2250,1200,2100,2250,2900,1650,2550,2300,2250,3050,2750,1900,1700,3850,2550,2450,3200,1550,2800,2250,1967,2200,3000,2867,1600,2550,2550,2000,2900,2400,3100,1900,2300,3250,2500,2100,2100,3325,1800,3225,1400,2400,2500,1800,3275,2225,1650,2900,2300,3200,1475,2025,2300,1950,1800,2900,2250,3050,2200,3100,2400,2250,2625,5200,3325,2925,2000,2400,2100,3725,3025,1900,3000,2850,2300,2000,1600,1900,1950,3200,1850,1800,3500,2350,2275,3050,2150,2750,2200,1800,2175,2750,3275,2625,2625,2000]},\"columns\":[{\"id\":\"Color\",\"name\":\"Color\",\"type\":\"factor\"},{\"id\":\"Spine\",\"name\":\"Spine\",\"type\":\"factor\"},{\"id\":\"Width\",\"name\":\"Width\",\"type\":\"numeric\"},{\"id\":\"Satellite\",\"name\":\"Satellite\",\"type\":\"numeric\"},{\"id\":\"Weight\",\"name\":\"Weight\",\"type\":\"numeric\"}],\"filterable\":true,\"searchable\":true,\"defaultPageSize\":10,\"onClick\":\"select\",\"highlight\":true,\"outlined\":true,\"bordered\":true,\"striped\":true,\"dataKey\":\"5914f207c0f2ef2cc3fdef7205324a2c\"},\"children\":[]},\"class\":\"reactR_markup\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n# Part 1: Exploratory Data Analysis\n\n## Variable Exploration\n\n### Explore the response variable: Satellite\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crab, mapping = aes(x = Satellite)) + \n  geom_histogram(fill = \"gray\", color = \"black\", binwidth = 0.5) + \n  xlab(\"Satellite\") +\n  ylab(\"Count of crabs\") +\n  geom_vline(xintercept = mean(crab$Satellite), color = \"red\"\n             , linetype = \"dashed\", size = 1) +\n  theme_classic() +\n  guides(color = FALSE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n### Explore Individual Predictors:\n\n#### Explore Color\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(crab$Color) %>% prop.table() %>% signif(3) %>% pander::pander()\n```\n\n::: {.cell-output-display}\n\n--------------------------------\n   2        3       4       5   \n-------- ------- ------- -------\n 0.0694   0.549   0.254   0.127 \n--------------------------------\n\n\n:::\n\n```{.r .cell-code}\nsumStatsCol <- crab %>%\n  group_by(Color) %>% \n  summarise(n = n(),\n            mntotal = mean(Satellite),\n            vartotal = var(Satellite), \n            logmntotal = log(mntotal)\n            )\nsumStatsCol\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  Color     n mntotal vartotal logmntotal\n  <fct> <int>   <dbl>    <dbl>      <dbl>\n1 2        12    4.08     9.72      1.41 \n2 3        95    3.29    10.3       1.19 \n3 4        44    2.23     6.74      0.801\n4 5        22    2.05    13.1       0.716\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(sumStatsCol, aes(x = Color, y = logmntotal)) +\n  geom_point(size = 3) +\n  geom_smooth(method = \"loess\") +\n  xlab(\"Crab Color\") +\n  ylab(\"Log of the empirical mean number of Satellites\") +\n  labs(title = \"Color Vs. Log of empirical mean of Satellites\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# check mean = variance\nggplot(sumStatsCol, aes(x = mntotal, y = vartotal)) + \n  geom_point( size = 3) +\n  geom_smooth(method = \"loess\") + \n  geom_abline(slope = 1, intercept = 0,\n              col = \"red\", size = 1, linetype = 3) +\n  ylim(-2.5, 15) +\n  xlab(\"Empirical mean number of Satellites per crab (by Color)\") +\n  ylab(\"Empirical variance in number of Satellites per crab (by Color)\") + \n  labs(title = \"Mean = Variance\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\n#### Explore Spine\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(crab$Spine) %>% prop.table() |> signif(3) %>% pander::pander()\n```\n\n::: {.cell-output-display}\n\n------------------------\n   1       2        3   \n------- -------- -------\n 0.214   0.0867   0.699 \n------------------------\n\n\n:::\n\n```{.r .cell-code}\nsumStatsSp <- crab %>%\n  group_by(Spine) %>% \n  summarise(n = n(),\n            mntotal = mean(Satellite),\n            vartotal = var(Satellite), \n            logmntotal = log(mntotal)\n            )\nsumStatsSp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  Spine     n mntotal vartotal logmntotal\n  <fct> <int>   <dbl>    <dbl>      <dbl>\n1 1        37    3.65    11.5       1.29 \n2 2        15    2        5.57      0.693\n3 3       121    2.81     9.82      1.03 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(sumStatsSp, aes(x = Spine, y = logmntotal)) +\n  geom_point(size = 3) +\n  geom_smooth(method = \"loess\") +\n  xlab(\"Crab Spine\") +\n  ylab(\"Log of the empirical mean number of Satellites\") +\n  labs(title = \"Spine Vs. Log of empirical mean of Satellites\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# check mean = variance\nggplot(sumStatsSp, aes(x = mntotal, y = vartotal)) + \n  geom_point( size = 3) +\n  geom_smooth(method = \"loess\") + \n  geom_abline(slope = 1, intercept = 0,\n              col = \"red\", size = 1, linetype = 3) +\n  ylim(-1, 12.5) +\n  xlab(\"Empirical mean number of Satellites per crab (by Spine)\") +\n  ylab(\"Empirical variance in number of Satellites per crab (by Spine)\") + \n  labs(title = \"Mean = Variance\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n:::\n\n\n#### Explore Width\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumStatsWidth <- crab %>%\n  group_by(Width) %>% \n  summarise(n = n(),\n            mntotal = mean(Satellite),\n            vartotal = var(Satellite), \n            logmntotal = log(mntotal)\n            )\n# sumStatsWidth\nggplot(sumStatsWidth, aes(x = Width, y = logmntotal)) +\n  geom_point() +\n  geom_smooth(method = \"loess\") +\n  xlab(\"Crab Width\") +\n  ylab(\"Log of the empirical mean number of Satellites\") +\n  labs(title = \"Width Vs. Log of empirical mean of Satellites\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# check mean = variance\nggplot(sumStatsWidth, aes(x = mntotal, y = vartotal)) + \n  geom_point() +\n  geom_smooth(method = \"loess\") + \n  geom_abline(slope = 1, intercept = 0,\n              col = \"red\", size = 1, linetype = 3) +\n  xlab(\"Empirical mean number of Satellites per crab (by Width)\") +\n  ylab(\"Empirical variance in number of Satellites per crab (by Width)\") + \n  labs(title = \"Mean = Variance\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n:::\n\n\n#### Explore Weight\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumStatsWght <- crab %>%\n  group_by(Weight) %>% \n  summarise(n = n(),\n            mntotal = mean(Satellite),\n            vartotal = var(Satellite), \n            logmntotal = log(mntotal)\n            )\n# sumStatsWght\nggplot(sumStatsWght, aes(x = Weight, y = logmntotal)) +\n  geom_point() +\n  geom_smooth(method = \"loess\") +\n  xlab(\"Crab Weight\") +\n  ylab(\"Log of empirical mean of Satellites\") +\n  labs(title = \"Weight Vs. Log of empirical mean of Satellites\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# check mean = variance\nggplot(sumStatsWght, aes(x = mntotal, y = vartotal)) + \n  geom_point() +\n  geom_smooth(method = \"loess\") + \n  geom_abline(slope = 1, intercept = 0,\n              col = \"red\", size = 1, linetype = 3) +\n  xlab(\"Empirical mean number of Satellites per crab (by Weight)\") +\n  ylab(\"Empirical variance in number of Satellites per crab (by Weight)\") + \n  xlim(0, 7.25)+\n  labs(title = \"Mean = Variance\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n:::\n\n\n### Explore predictor Combinations:\n\n#### Explore by Width and Color\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumStatsWidCol <- crab %>% \n  group_by(Color, Width) %>%\n  summarise(n = n(),\n            mntotal = mean(Satellite),\n            vartotal = var(Satellite),\n            logmntotal = log(mntotal,)\n            )\n# sumStatsWidCol\nggplot(sumStatsWidCol, aes(x = Width, y = logmntotal, color = Color)) +\n  geom_point(size = 2)+\n  geom_smooth(method = \"loess\", se=FALSE) +\n  labs(title = \"Width & Color Predicts Log of empirical mean of Satellites\") +\n  xlab(\"Widths of Crab\") +\n  ylab(\"Log empirical mean Satellite Count\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# mean = variance\nggplot(sumStatsWidCol, aes(x = mntotal, y = vartotal)) +\n  geom_point(size = 2)+\n  geom_smooth(method = \"loess\") +\n  geom_abline(slope = 1, intercept = 0,\n              col = \"red\", size = 2, linetype = 3) +\n  xlim(0, 8)+\n  labs(title = \"Mean = Variance\") +\n  xlab(\"Mean total\") +\n  ylab(\"Variance Total\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n:::\n\n\n#### Explore by Weight and Color\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumStatsWghtCol <- crab %>% \n  group_by(Color, Weight) %>%\n  summarise(n = n(),\n            mntotal = mean(Satellite),\n            vartotal = var(Satellite),\n            logmntotal = log(mntotal)\n            )\n# sumStatsWghtCol\nggplot(sumStatsWghtCol, aes(x = Weight, y = logmntotal, color = Color)) +\n  geom_point(size = 3)+\n  geom_smooth(method = \"loess\", se=FALSE)+\n  xlab(\"Weight of Crab\") +\n  ylab(\"Log empirical mean Satellite Count\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(sumStatsWghtCol, aes(x = mntotal, y = vartotal)) +\n  geom_point(size = 2)+\n  geom_smooth(method = \"loess\") +\n  geom_abline(slope = 1, intercept = 0,\n              col = \"red\", size = 2, linetype = 3) +\n  xlim(0, 8) +\n  labs(title = \"Mean = Variance\") +\n  xlab(\"Mean total\") +\n  ylab(\"Variance Total\") +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n:::\n\n\n## Questions\n\n### 1. Any evidence you consider to evaluate Poisson regression's mean = variance assumption (with your thoughts on the validity of the assumption)?\n\n### 2. Plots (with commentary) that explore the utility of the available explanatory variables for predicting number of satellites\n\n# Part 2 :Poisson Regression Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrab <- crab %>% mutate(\n  color4 = ifelse(Color == 4, 1, 0)\n) # mutated this since among the colors, dark medium (4) is most \n  # and only significant predictor\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmod = glm(formula = Satellite ~ Weight + Width + I(Width^2) + color4,\n          family = \"poisson\", data = crab\n          )\n```\n:::\n\n\n## 1. Include a summary of the model output\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Satellite ~ Weight + Width + I(Width^2) + color4, \n    family = \"poisson\", data = crab)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-3.2243  -1.8311  -0.5256   0.7874   4.7646  \n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -2.159e+01  5.433e+00  -3.974 7.07e-05 ***\nWeight       6.948e-04  1.800e-04   3.860 0.000114 ***\nWidth        1.561e+00  3.991e-01   3.911 9.19e-05 ***\nI(Width^2)  -2.892e-02  7.464e-03  -3.875 0.000107 ***\ncolor4      -2.335e-01  1.135e-01  -2.058 0.039628 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 632.79  on 172  degrees of freedom\nResidual deviance: 538.64  on 168  degrees of freedom\nAIC: 903.94\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n## 2. Conduct a hypothesis test to determine if there is evidence that this model is useful\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodRed = glm(formula = Satellite ~ Weight + Width,\n             family = \"poisson\", data = crab\n             )\nsummary(modRed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Satellite ~ Weight + Width, family = \"poisson\", \n    data = crab)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.9309  -1.9702  -0.5478   0.9700   4.9904  \n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)   \n(Intercept) -1.2952111  0.8988960  -1.441  0.14962   \nWeight       0.0004470  0.0001586   2.818  0.00483 **\nWidth        0.0460765  0.0467497   0.986  0.32433   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 632.79  on 172  degrees of freedom\nResidual deviance: 559.90  on 170  degrees of freedom\nAIC: 921.2\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n\\$H_O: B_3=0 , B_4=0 \\$ $H_A: B_3\\not=0 , B_4\\not= 0$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDevRed = 559.90\nDevFull = 538.64\ndf = 170 - 168\npchisq(DevRed-DevFull, df, lower.tail = FALSE) %>% signif(digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.418e-05\n```\n\n\n:::\n:::\n\n\nWe can conclude that based off the likelihood ratio test, there is evidence that the full model is the better choice ($ts=21.26$,$df = 2$,$P\\approx0$)\n\n## 3.Include an interpretation of the estimated coefficient on carapace width. Include a discussion about the significance of carapace width in the model\n\nWe can interpret the estimated coefficient on carapace width as.... For every unit added to the width, the difference in the logs of expected satellite count changes by 1.369351, given the other predictor variables in the model are held constant.\n\n## 4. Conduct a hypothesis test to determine if there is evidence that the model has significant lack of fit\n\n$H_O:B_1=0,B_2=0,B_3=0,B_4=0$\n$H_A:$ At least one $B_i\\not=0$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npchisq(554.17, df = 169, lower.tail = FALSE) %>% signif(digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.655e-42\n```\n\n\n:::\n:::\n\n\nThere is no evidence that the model has significant lack of fit, with $P\\approx0$\n\n# Part 3: Poisson Regression Model with Overdispersion\n\nFit a Poisson Regression model that adjusts for overdispersion. Provide a summary of your model output\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodQ = glm(formula = Satellite ~ Weight + Width + I(Width^2) + color4,\n           family = \"quasipoisson\", data = crab, offset = log(Width)\n           )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(modQ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Satellite ~ Weight + Width + I(Width^2) + color4, \n    family = \"quasipoisson\", data = crab, offset = log(Width))\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-3.2239  -1.8309  -0.5255   0.7870   4.7646  \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)  \n(Intercept) -2.340e+01  9.603e+00  -2.436   0.0159 *\nWeight       6.947e-04  3.182e-04   2.183   0.0304 *\nWidth        1.488e+00  7.055e-01   2.109   0.0364 *\nI(Width^2)  -2.826e-02  1.319e-02  -2.142   0.0336 *\ncolor4      -2.335e-01  2.006e-01  -1.164   0.2461  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for quasipoisson family taken to be 3.124796)\n\n    Null deviance: 606.45  on 172  degrees of freedom\nResidual deviance: 538.63  on 168  degrees of freedom\nAIC: NA\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(modQ)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-4.png){width=672}\n:::\n:::\n\n\n## 1. if you believe there is a significant problem with overdispersion\n\n*Dispersion parameter (No overdispersion, if 1 or less)*\n\nYes there is a problem with the dispersion parameter, since it is greater than 1, therefore implying that the model has been overdispersed.\n\n$\\hat{\\phi}=3.124796$ considered a scalar\n\n## 2. the impact that adjusting for overdispersion has on the performance of your model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LOF-test\npchisq(\n  summary(modQ)$deviance,\n  summary(modQ)$df.residual, \n  lower.tail = FALSE\n       ) %>% signif(digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.053e-40\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodred = glm(formula = Satellite ~ Weight + Width + color4,\n             family = \"quasipoisson\", data = crab, offset = log(Width)\n             )\nsummary (modred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Satellite ~ Weight + Width + color4, family = \"quasipoisson\", \n    data = crab, offset = log(Width))\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.9902  -1.9670  -0.5098   0.9451   4.8609  \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)  \n(Intercept) -3.3276750  1.6023276  -2.077   0.0393 *\nWeight       0.0004571  0.0002811   1.626   0.1058  \nWidth        0.0001963  0.0829475   0.002   0.9981  \ncolor4      -0.2238217  0.2016238  -1.110   0.2685  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for quasipoisson family taken to be 3.129959)\n\n    Null deviance: 606.45  on 172  degrees of freedom\nResidual deviance: 555.05  on 169  degrees of freedom\nAIC: NA\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n$H_O: B_3 = 0, B_4 = 0$ \\$H_A: B_3 \\not= 0, B_4 \\not= 0 \\$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#LRT\nanova(modred, modQ, test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: Satellite ~ Weight + Width + color4\nModel 2: Satellite ~ Weight + Width + I(Width^2) + color4\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)  \n1       169     555.05                       \n2       168     538.63  1   16.417   0.0219 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# LRT\nDevRed = 555.05\nDevFull = 538.63\ndf = 169 - 168\npchisq(DevRed-DevFull, df, lower.tail = FALSE) %>% signif(digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.075e-05\n```\n\n\n:::\n:::\n\n\nCan conclude that the full model is the better choice, according to the likelihood ratio test results.... \\$ts = 16.417, df = 2, P=0.0219 \\$\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/core-js-2.5.3/shim.min.js\"></script>\n<script src=\"../../site_libs/react-18.2.0/react.min.js\"></script>\n<script src=\"../../site_libs/react-18.2.0/react-dom.min.js\"></script>\n<script src=\"../../site_libs/reactwidget-1.0.0/react-tools.js\"></script>\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/reactable-0.4.4/reactable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/reactable-binding-0.4.4/reactable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}